# Generated by Django 5.0.6 on 2024-06-12 01:11

import dcc.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('emp_weight', models.IntegerField(choices=dcc.models.Choices.IntegerChoices100, default=1)),
                ('emp_status', models.IntegerField(choices=dcc.models.Choices.StatusChoices, default=1)),
                ('emp_post', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='dcc.post')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=200)),
                ('sec_head', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_section', to='dcc.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='dcc.section'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv_name', models.CharField(max_length=200)),
                ('required_documents', models.TextField()),
                ('serv_fee', models.PositiveIntegerField()),
                ('serv_time', models.CharField(max_length=200)),
                ('serv_section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='services', to='dcc.section')),
            ],
        ),
    ]
