# Generated by Django 5.0.6 on 2024-06-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0002_post_employee_email_employee_emp_weigth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_post',
            field=models.OneToOneField(default='Not', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='dcc.post'),
        ),
    ]
