# Generated by Django 5.0.6 on 2024-06-17 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0004_publicrepresentativepost_publicrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=200, verbose_name='पद'),
        ),
        migrations.AlterField(
            model_name='publicrepresentativepost',
            name='name',
            field=models.CharField(max_length=100, verbose_name='नाम थर'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_head',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_section', to='dcc.employee', verbose_name='शाखा प्रमुख'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_name',
            field=models.CharField(max_length=200, verbose_name='शाखा'),
        ),
    ]
