# Generated by Django 5.0.6 on 2024-06-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0004_alter_employee_emp_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_post',
            field=models.OneToOneField(default='Admin', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='dcc.post'),
        ),
    ]
