# Generated by Django 5.0.6 on 2024-06-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0006_rename_publicrepresentative_publicrep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrep',
            name='phone_number',
            field=models.PositiveBigIntegerField(null=True, unique=True, verbose_name='सम्पर्क नं'),
        ),
    ]
