# Generated by Django 5.0.6 on 2024-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcc', '0007_publicrep_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicrep',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
